[package]
name = "exonum-storage-derive"
version = "0.1.0"
authors = ["The Exonum Team <exonum@bitfury.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.14.2"
quote = "0.6.3"
proc-macro2 = "0.4.6"
exonum = { path = "../exonum" }
